// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO1r_hq5osxwlcxOXy2ATlgpx6NuFbWf8',
    appId: '1:80196511557:web:36a01c39db4b0683d6002c',
    messagingSenderId: '80196511557',
    projectId: 'social-zklogin',
    authDomain: 'social-zklogin.firebaseapp.com',
    storageBucket: 'social-zklogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJZ9eg7o3AvLT3VM619qc1r0OvrlG_Fw',
    appId: '1:80196511557:android:02f51aec1d75cec2d6002c',
    messagingSenderId: '80196511557',
    projectId: 'social-zklogin',
    storageBucket: 'social-zklogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Fs1GPoHT4msBT7s7WjVdP-ByFF3vrMY',
    appId: '1:80196511557:ios:9b469caea4b073b5d6002c',
    messagingSenderId: '80196511557',
    projectId: 'social-zklogin',
    storageBucket: 'social-zklogin.appspot.com',
    iosBundleId: 'com.example.socialToZklogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Fs1GPoHT4msBT7s7WjVdP-ByFF3vrMY',
    appId: '1:80196511557:ios:b7132bae714b0870d6002c',
    messagingSenderId: '80196511557',
    projectId: 'social-zklogin',
    storageBucket: 'social-zklogin.appspot.com',
    iosBundleId: 'com.example.socialToZklogin.RunnerTests',
  );
}
